name: base
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
- python=3.12
- bzip2
- nanoplot<=1.43.0
- seqkit<=2.9.0
- pbmm2<=1.16.0
- samtools<=1.21
- bcftools<=1.21
- bedtools<=2.31.1
- pip
- pip:
  - matplotlib
  - seaborn
  - pyarrow
  - pandas
